[profile.release]
lto = true

[profile.release.package.anchor-cli]
codegen-units = 1

[workspace]
members = [
    "leetcode-two-sum",
    "codility-possible-string-palindrome",
    "codility-binary-gap",
    "codility-array-rotation",
    "codility-frog-jump",
    "leetcode-median-of-two-sorted-arrays",
    "leetcode-queue-reconstruction-by-height"
]
