[profile.release]
lto = true

[profile.release.package.anchor-cli]
codegen-units = 1

[workspace]
members = [
    "leetcode-two-sum",
    "codility-possible-string-palindrome",
    "codility-binary-gap",
    "codility-array-rotation",
    "codility-frog-jump",
    "leetcode-queue-reconstruction-by-height",
    "leetcode-add-two-numbers",
    "leetcode-basic-calculator-ii",
]
