[package]
name = "leetcode-check-if-number-has-equal-digit-count-and-digit-value"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
